### ISSUE TITLE
Detailed Placement Error

### ISSUE THREAD

**Issue by HongYuLou** [cuhk-eda/Xplace#14]
Hi,
When I ran the iccad2017 benchmark without fence region, the following problems occurred in three cases: They are pci_bridge32_b_md2, pci_bridge32_b_md3, def_perf_a_md2, but when I use the same lef def to run your ripple, it works fine.I don't know the reason, could you please explain it?
[   1.641] ------- Start DP -------
[   1.645] Finish setup database. #siteX: 4000 #siteY: 400
[   1.645] Start running Macro Legalization... #Macros: 954, #MovMacros: 585.
[   1.645] WARNING Including fixed macros. LP formula may be infeasible.
/lib/python3.11/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.
  warnings.warn(problem)
Traceback (most recent call last):
  File "/project/Xplace/main.py", line 106, in <module>
    main()
  File "/project/Xplace/main.py", line 102, in main
    run_placement_main(args, logger)
  File "/project/Xplace/src/run_placement.py", line 41, in run_placement_main
    run_placement_single(args, logger)
  File "/project/Xplace/src/run_placement.py", line 10, in run_placement_single
    res = run_placement_main_nesterov(args, logger)
  File "/project/Xplace/src/run_placement_nesterov.py", line 419, in run_placement_main_nesterov
    node_pos, dp_hpwl, top5overflow, lg_time, dp_time = detail_placement_main(
  File "/project/Xplace/src/detail_placement.py", line 757, in detail_placement_main
    node_pos, dp_hpwl, lg_time, dp_time = default_detail_placement(
  File "/project/Xplace/src/detail_placement.py", line 698, in default_detail_placement
    node_pos = run_lg(node_pos, data, args, logger)
  File "/project/Xplace/src/detail_placement.py", line 374, in run_lg
    macro_legalization_main(node_pos, data, args, logger, lg_rawdb)
  File "/project/Xplace/src/detail_placement.py", line 354, in macro_legalization_main
    run_macro_legalization(node_pos, data, lg_rawdb, args, logger)
  File "/project/Xplace/src/detail_placement.py", line 332, in run_macro_legalization
    macro_pos, solve_success = macro_legalization_multi(macro_info, args, logger)
  File "/project/Xplace/src/core/macro_legalization.py", line 909, in macro_legalization_multi
    edge_type, _, _ = longest_path_refinement(macro_pos, macro_size, macro_fixed, die_info, die_ll, die_ur,
  File "/project/Xplace/src/core/macro_legalization.py", line 372, in longest_path_refinement
    g_x = ig.Graph.Adjacency(adj_matrix[:,:,0], mode= "directed")
NameError: name 'ig' is not defined. Did you mean: 'g'?

**Comment by liulixinkerry** [comment]
This is `igraph` python library. Please use pip or conda to install it. My version is `0.11.5`.

**Comment by HongYuLou** [comment]
> This is python library. Please use pip or conda to install it. My version is .`igraph``0.11.5`

Thank you for your answer.
I would like to ask another question, can you provide the Modified ISPD 2015 Benchmark used in your paper TCAD2021 on Pin-Accessible Legalization for Mixed-Cell-Height Circuits.
